### ISSUE TITLE
Error in node 6.4.0

### ISSUE THREAD

**Issue by DonKanallie** [cnect/sails-sqlserver#46]
Hi,

my application crashes after update to node 6.4.0

`RangeError: Offset is out of bounds
    at RangeError (native)
    at Buffer.write (buffer.js:778:21)
    at WritableTrackingBuffer.writeString (/Users/jonesBoi/Anyline/NewStuff/backend/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/tracking-buffer/writable-tracking-buffer.js:212:32)
    at Login7Payload.addVariableDataString (/Users/jonesBoi/Anyline/NewStuff/backend/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/login7-payload.js:225:23)
    at Login7Payload.createVariableData (/Users/jonesBoi/Anyline/NewStuff/backend/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/login7-payload.js:191:10)
    at new Login7Payload (/Users/jonesBoi/Anyline/NewStuff/backend/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/login7-payload.js:112:21)
    at Connection.sendLogin7Packet (/Users/jonesBoi/Anyline/NewStuff/backend/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/connection.js:841:15)
    at Connection.STATE.SENT_PRELOGIN.events.tls (/Users/jonesBoi/Anyline/NewStuff/backend/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/connection.js:114:16)
    at Connection.dispatchEvent (/Users/jonesBoi/Anyline/NewStuff/backend/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/connection.js:752:59)
    at Connection.processPreLoginResponse (/Users/jonesBoi/Anyline/NewStuff/backend/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/connection.js:821:19)
    at Connection.STATE.SENT_PRELOGIN.events.message (/Users/jonesBoi/Anyline/NewStuff/backend/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/connection.js:102:23)
    at Connection.dispatchEvent (/Users/jonesBoi/Anyline/NewStuff/backend/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/connection.js:752:59)
    at MessageIO.<anonymous> (/Users/jonesBoi/Anyline/NewStuff/backend/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/connection.js:685:22)
    at emitNone (events.js:86:13)
    at MessageIO.emit (events.js:185:7)
    at MessageIO.eventData (/Users/jonesBoi/Anyline/NewStuff/backend/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/message-io.js:58:21)
    at Socket.<anonymous> (/Users/jonesBoi/Anyline/NewStuff/backend/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/message-io.js:3:59)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
`

I think it's related to [this](https://github.com/balderdashy/sails-mysql/issues/321)

**Comment by matuck** [comment]
This does look like the same error.  I have already sent a pull request to fix this should they accept it.

**Comment by matuck** [comment]
This does look to be a related issue.  In the other issue I fixed it by updating the underlying MySQL dependency.  I created a pull request for it.  Probably need to updating the underlying MS SQL  dependency.
