### ISSUE TITLE
RequestError: Incorrect syntax near ')'.

### ISSUE THREAD

**Issue by victorsosa** [cnect/sails-sqlserver#54]
Hi,

using v0.10.8 I try to do a call create I got this error:

```
{ RequestError: Incorrect syntax near ')'.
    at Connection.<anonymous> (/home/vns/workspace/sellfastRS/node_modules/sails-sqlserver/node_modules/mssql/lib/tedious.js:658:17)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Parser.<anonymous> (/home/vns/workspace/sellfastRS/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/connection.js:444:15)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser.nextToken (/home/vns/workspace/sellfastRS/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/token/token-stream-parser.js:91:18)
    at Parser.addBuffer (/home/vns/workspace/sellfastRS/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/token/token-stream-parser.js:68:17)
    at Connection.sendDataToTokenStreamParser (/home/vns/workspace/sellfastRS/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/connection.js:891:35)
    at Connection.data (/home/vns/workspace/sellfastRS/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/connection.js:275:23)
    at Connection.dispatchEvent (/home/vns/workspace/sellfastRS/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/connection.js:752:59)
    at MessageIO.<anonymous> (/home/vns/workspace/sellfastRS/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/connection.js:680:22)
    at emitOne (events.js:96:13)
    at MessageIO.emit (events.js:188:7)
    at MessageIO.eventData (/home/vns/workspace/sellfastRS/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/message-io.js:56:12)
    at Socket.<anonymous> (/home/vns/workspace/sellfastRS/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/message-io.js:3:59)
  name: 'RequestError',
  message: 'Incorrect syntax near \')\'.',
  code: 'EREQUEST',
  number: 102,
  lineNumber: 1,
  state: 1,
  class: 15,
  serverName: 'DESKTOP-4UM8OS5',
  procName: '',
  precedingErrors: [] }
[Error (E_UNKNOWN) Encountered an unexpected error] Details:  RequestError: Incorrect syntax near ')'.
```

any ideas? it seems like the adapter is generating the wrong syntax; in the case of a normal find() call it is working properly.

**Comment by victorsosa** [comment]
this is the statement generated like:
`create statement: INSERT INTO [Clientes] () VALUES (); SELECT @@IDENTITY AS [id]`

all the values and fields are missing

**Comment by victorsosa** [comment]
`create statement: INSERT INTO [Clientes] () VALUES (); SELECT @@IDENTITY AS [id]`
 
the values and fields are empty in the query; I make sure that I am passing the parameters to the create method

**Comment by victorsosa** [comment]
closed, my model need to have all the attributes defined
