### ISSUE TITLE
doesn't work with sails@beta 

### ISSUE THREAD

**Issue by gabrythe23** [cnect/sails-sqlserver#58]
I've received an error with: 

- sails@beta 1.0.0-36 
- npm 5.0.3
- node 6.10.0

The issue raises with Ubuntu 16 and macOS 10.12.4

```
Error: 
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

The adapter used by the `default` datastore is not compatible with
the current version of Sails/Waterline.

The adapter should expose a valid `adapterApiVersion`.

If you're using the beta release of Sails 1.0, try:
npm install --save sails-sqlserver@beta
```

If I try to run `npm install --save sails-sqlserver@beta` npm says that there's no compatible version found.

```
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "sails-sqlserver@beta"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: sails-sqlserver@beta
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.10.8, 0.10.7, 0.10.4, 0.10.3, 0.10.2
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/<folder>/npm-debug.log

```

**Comment by alexanderdevm** [comment]
any updates, it would be nice if there was support for mssql with sailsjs 1.0

**Comment by Karnith** [comment]
I'd like to know this as well...

**Comment by chaostheory** [comment]
This is an important issue given that the sailsjs team recommends using sails 1.0 beta for new projects

**Comment by SpaceG** [comment]
i have the same issue here with mongo DB

i dont know how to fix it, and what i have to do, now, to fix it. anybody here? peace 

```
 info: Starting app...

/Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/lib/check-adapter-compatibility.js:59
    throw flaverr('E_NOT_COMPATIBLE', new Error(
    ^

Error: 
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

The adapter used by the `localDiskDb` datastore is not compatible with
the current version of Sails/Waterline.

The adapter should expose a valid `adapterApiVersion`.

If you're using the beta release of Sails 1.0, try:
npm install --save sails-disk@beta

-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

    at checkAdapterCompatibility (/Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/lib/check-adapter-compatibility.js:59:39)
    at _eachRelevantDatastoreName (/Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/lib/initialize.js:424:9)
    at arrayEach (/Users/jh/Desktop/gitlist Kopie 2/node_modules/@sailshq/lodash/lib/index.js:1463:13)
    at Function.<anonymous> (/Users/jh/Desktop/gitlist Kopie 2/node_modules/@sailshq/lodash/lib/index.js:3525:13)
    at async.auto._checkAdapterCompatibility (/Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/lib/initialize.js:416:9)
    at runTask (/Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/node_modules/async/dist/async.js:1660:17)
    at /Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/node_modules/async/dist/async.js:1602:17
    at processQueue (/Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/node_modules/async/dist/async.js:1612:17)
    at taskComplete (/Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/node_modules/async/dist/async.js:1630:13)
    at /Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/node_modules/async/dist/async.js:1653:21
    at /Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/node_modules/async/dist/async.js:339:31
    at /Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/node_modules/async/dist/async.js:847:20
    at async.auto._doubleCheckMigration (/Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/lib/initialize.js:315:16)
    at runTask (/Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/node_modules/async/dist/async.js:1660:17)
    at /Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/node_modules/async/dist/async.js:1602:17
    at processQueue (/Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/node_modules/async/dist/async.js:1612:17)
    at taskComplete (/Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/node_modules/async/dist/async.js:1630:13)
    at /Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/node_modules/async/dist/async.js:1653:21
    at /Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/node_modules/async/dist/async.js:339:31
    at /Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/node_modules/async/dist/async.js:847:20
    at async.auto._productionCheck (/Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/lib/initialize.js:297:14)
    at runTask (/Users/jh/Desktop/gitlist Kopie 2/node_modules/sails-hook-orm/node_modules/async/dist/async.js:1660:17)
codes-Mac-mini:gitlist Kopie 2 jh$ 

```

**Comment by TamizhArasiPalanivel** [comment]
same issue here for    "sails-sqlserver": "^0.10.8"  "sails": "^1.1.0", please let me know if anybody could solve this

Error:
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

The adapter used by the `default` datastore is not compatible with
the current version of Sails/Waterline.

The adapter should expose a valid `adapterApiVersion`.

If you're using Sails ≥1.0, try:
npm install sails-sqlserver@latest --save

-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
