### ISSUE TITLE
UnhandledPromiseRejectionWarning: ConnectionError: Failed to connect to *******.database.windows.net:11218 in 60000ms

### ISSUE THREAD

**Issue by praveen4554** [cnect/sails-sqlserver#62]
my sails app server config
sqlserver: {
        adapter: 'sails-sqlserver',
        user: process.env.dbuser || '********',
        password: process.env.dbpassword || '*****',
        host: process.env.sqlserver || '*****',
        database: process.env.dbname || '*****',
        options: {
            encrypt: true   // use this for Azure databases
        }
    },

it will be running correctly in local but when deploy my application in azure vm instance it throws error 
(node:103215) UnhandledPromiseRejectionWarning: ConnectionError: Failed to connect to *****.database.windows.net:11218 in 60000ms
    at Connection.<anonymous> (/home/mythri/HR/Server/node_modules/sails-sqlserver/node_modules/mssql/lib/tedious.js:353:25)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Connection.connectTimeout (/home/mythri/HR/Server/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/connection.js:709:10)
    at Timeout._onTimeout (/home/mythri/HR/Server/node_modules/sails-sqlserver/node_modules/mssql/node_modules/tedious/lib/connection.js:3:59)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)

can anyone help me to figured out

**Comment by JonasLaux** [comment]
Any progress on this?

**Comment by praveen4554** [comment]
Issue resolved

**Comment by JonasLaux** [comment]
how?
